### ISSUE TITLE
Mixed ploidy genotype_call_dataset

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#243]
#### Overview
 
This is a proposal to support mixed-ploidy data within a single `genotype_call_dataset`. 
It aims to have minimal impact on existing code and to avoid causing issues when implementing diploid only functionality in future.
Criticism is very welcome!

Within the VCF specification, mixed-ploidy data can be defined by using a mixture of genotype string (GT) lengths.
For example the following encodes one diploid and two tetraploid individuals:
```
#CHROM    POS    ID    REF    ALT   QUAL    FILTER    INFO         FORMAT    SAMPLE1    SAMPLE2    SAMPLE3
1         1000   .     C      G     60      PASS      NS=3;DP=30   GT        0/0/0/0    0/0        0/0/0/1
1         2000   .     T      A     60      PASS      NS=3;DP=30   GT        0/0/0/0    0/1        0/1/./.
```

#### Implementation

I think that the simplest approach to supporting mixed ploidy in a `genotype_call_dataset` is to introduce a second sentinel value e.g. `-2` which indicates a *non-allele*.
The above VCF would translate to the array:
```python
call_genotype = da.array([
    [[0, 0, 0, 0], [0, 0, -2, -2], [0, 0, 0, 1]], 
    [[0, 0, 0, 0], [0, 1, -2, -2], [0, 1, -1, -1]]
])
```

A convenience mask could also be created, similar to the one indicating missing values:
```python
call_genotype_mask = call_genotype == -1
call_genotype_non_allele = call_genotype < -1
```

we can also include the ploidy of each genotype call:
```python
call_genotype_ploidy = (~call_genotype_non_allele).sum(axis=-1)  # shape (variants, samples)
```

and ploidy across each sample or variant using `-1` to indicate mixed/inconsistent ploidy:
```python
sample_ploidy_fixed = (call_genotype_ploidy[0,:] == call_genotype_ploidy).all(axis=0)
sample_ploidy = xr.where(sample_ploidy_fixed, call_genotype_ploidy[0,:], -1)  # shape (samples,)

variant_ploidy_fixed = (call_genotype_ploidy[:,0] == call_genotype_ploidy.T).all(axis=0)
variant_ploidy = xr.where(variant_ploidy_fixed, call_genotype_ploidy[:,0], -1)  # shape (variants,)
```

#### Checking if a dataset has consistent ploidy

The most difficult aspect of this proposal is ensuring that mixed-ploidy datasets do not get used in a function that only supports diploid (or fixed ploidy) data.
Simply checking the ploidy dimension size ([e.g.](https://github.com/pystatgen/sgkit/blob/master/sgkit/stats/hwe.py#L163)) would no longer be reliable because it would only indicate the *maximum* ploidy. 
Calculating the actual ploidy of a (potentially mixed ploidy) dataset will ultimately require checking all genotype calls in the dataset for a value `<= -2`.

A workaround for this issue is to trust the user to specify if their data is mixed-ploidy or not during dataset creation by adding a `mixed_ploidy` argument (default=`False`) to `create_genotype_call_dataset` (or reader functions).
If this argument is False then `sample_ploidy` etc. can simply return the size of the ploidy dimension.
If it is true then `sample_ploidy` etc. are caluclated as above.
The value of the `mixed_ploidy` argument would be stored as a dataset attribute to enable a quick check for fixed-ploidy only functions. 
Functions that require ploidy to be fixed in the sample or variant dimension can check `sample_ploidy` or `variant_ploidy` repectively which will be quick if `mixed_ploidy=False`.

The alternative to letting the user specify `mixed_ploidy` is to check the `call_genotype` array for values `<= -2`.

#### Implications for existing code

This proposal would add a `mixed_ploidy` argument and attribute to `create_genotype_call_dataset` with a default value of `False`.
It would also insert the following dask arrays into a `genotype_call_dataset` :

- `call_genotype_non_allele` with shape `(variants, samples, ploidy)`
- `call_genotype_ploidy` with shape `(variants, samples)`
- `sample_ploidy` with shape `(samples,)`
- `variant_ploidy` with shape `(variants,)`

Existing code that checks for the ploidy of a dataset would need to check if the dataset is mixed-ploidy via the new attribute.
Some functions including `display_genotypes` would need to be adapted to handle mixed ploidy data.

**Comment by jeromekelleher** [comment]
Thanks for this @timothymillar, it seems like a really solid idea. We discussed this in the weekly call just now, and @eric-czech had a great question: how do you see this being used by library functions? I.e., what functionality within sgkit will need to be aware of mixed ploidy datasets? Ideally, I guess, most functions could treat mixed ploidy as missing data and only specific functions would need to understand the difference between -2 and -1 (i.e., we treat everything < 0 as missing data).

**Comment by timothymillar** [comment]
That's a good question @eric-czech .

> only specific functions would need to understand the difference between -2 and -1

Yes, the primary purpose of this proposal is to differentiate between a partial genotype and a genotype of lower ploidy (`0/1/./.` or `0/1`). This distinction is necessary to correctly filter partial genotypes (issue #223). It is also necessary to impute missing allele calls without altering a genotypes ploidy. The `display_genotypes` function is another example where this distinction is important.

> Ideally, I guess, most functions could treat mixed ploidy as missing data

Absolutely, core functionality like counting alleles can treat both -2 and -1 as missing data*.  Converting phased genotypes into haplotypes (see [scikit-allel](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#haplotypearray)) can also ignore the distinction from what I can tell.

I imagine that most statistical functionality will either use haplotype arrays or allele counts/frequencies rather than using genotype calls directly. If this is the case then that functionality will not need to be aware of the distinction between -2 and -1, though it may need to check the `mixed_ploidy` attribute.

For my use-case, I will primarily be filtering/imputing partial genotypes then converting to `call_allele_counts`. Most analysis will be performed using allele counts including observed-heterozygosity, gene-diversity, *F* and *F_ST* (or equivalents).
I'm also interested in haplotype diversity statistics though I need to do more research in this area.

Some future functionality may need to be aware of variant-wise or sample-wise ploidy but that functionality should do so by using the `sample_ploidy` and/or `variant_ploidy` arrays (it could also sum allele counts). Therefore, that functionality shouldn't need to make the distinction between -2 and -1. The `sample_ploidy` and `variant_ploidy` arrays are also useful for exploratory analysis such as counting the frequency of each cytotype.


*Note that the distinction between ploidy and copy-number variation is particularly important when converting to haplotypes.

**Comment by jeromekelleher** [comment]
Thanks @timothymillar, I like it. Seems very elegant to me.

**Comment by eric-czech** [comment]
Thanks for laying this out so clearly @timothymillar!

I have two more questions:

1) How do you imagine `create_genotype_call_dataset` would ever get called with those parameters?  I ask because I don't want to get stuck on the idea that those `create_*` functions are important.  They currently have fairly general names because they have a little utility outside of the context of loading plink/bgen data, but that utility doesn't extend much beyond unit testing (tbh I'd be happy renaming them like `create_(plink|bgen)_dataset` instead).  In other words, I don't see that function as being something users need to be aware of so if this data would only ever come from VCF then I can also imagine that there are some other hts-specific fields we will want to eventually include in a mixed ploidy dataset.  I'd like for the scope of those functions to stay fairly specific to a data generating process and mixing PLINK and VCF is a bad idea IMO -- the list of optional parameters will get too long and confusing otherwise.  I am envisioning something like a `create_mixed_ploidy_dataset` function that is used within an sgkit function that interprets VCF in an opinionated way.  Without that vcf-specific function, I don't actually think there needs to be any associated `create_*` method.  We do of course need to recognize these proposed changes in the semantics of the `call_genotype` variable everywhere though as well as document the semantics for these new variables.

2) Is there any reason not to store the `mixed_ploidy` attribute on the `call_genotype` DataArray instead?  The more we can avoid dataset attributes necessary for computation the better since they're fairly easy to accidentally drop in a workflow.  Even if that attribute needs to be propagated to data variables generated based on `call_genotype`, I think that would still be better than having a global `mixed_ploidy` attribute since there will be so many things in a dataset for which that property is irrelevant.  It would also preclude having fixed and mixed ploidy variables in the same dataset.

**Comment by timothymillar** [comment]
Thanks @jeromekelleher  and @eric-czech 

1. I had assumed that `create_genotype_call_dataset` was primarily for testing and example datasets. If it's primarily for plink/bgen then adding mixed ploidy arguments there may not make sense. I agree that a VCF specific function would be the way to go here. My comments above were more about the data-representation rather than IO. But I guess the next step for me to figure out how this would work with the existing VCF reader code.

2. storing the `mixed_ploidy` attribute on the `call_genotype` DataArray would make more sense. I'm not that familiar with xarray and didn't realize that this was an option 😄 

I'm now also wondering if `sample_ploidy`, `variant_ploidy` and `call_genotype_ploidy` should be implemented as separate functions to minimize dataset clutter. I don't imagine they will be needed that often and it's probably better to keep the API/model as simple as possible.

**Comment by tomwhite** [comment]
> the next step for me to figure out how this would work with the existing VCF reader code

The diploid assumption for VCF is here: https://github.com/pystatgen/sgkit-vcf/blob/master/sgkit_vcf/vcf_reader.py#L64. To get going on the VCF implementation, I would recommend ignoring the multiple VCF/partitioning code, and get i) non-diploid, ii) mixed-ploidy working in the sequential case. (Here's a test for small VCFs that just exercises the sequential path: https://github.com/pystatgen/sgkit-vcf/blob/master/sgkit_vcf/tests/test_vcf_reader.py#L15.)

From an API point of view, we could assume fixed ploidy unless the user tells us otherwise.

> I'd be happy renaming them like `create_(plink|bgen)_dataset` instead

+1. I've opened https://github.com/pystatgen/sgkit/issues/252 to remove them from the API.

**Comment by eric-czech** [comment]
> My comments above were more about the data-representation rather than IO. 

Your proposal for the representation sounds great.  I'm certainly on board with the few changes that will affect fixed-ploidy code too.

> But I guess the next step for me to figure out how this would work with the existing VCF reader code.

👍

Do you already know how cyvcf2 distinguishes between non-alleles and missing alleles (if at all)?  I was wondering what https://github.com/pystatgen/sgkit-vcf/blob/master/sgkit_vcf/vcf_reader.py#L107 would return for that.

FYI I'm assuming that as we pull more things out of VCF, `create_genotype_call_dataset` will no longer be used in https://github.com/pystatgen/sgkit-vcf/blob/master/sgkit_vcf/vcf_reader.py#L122.  I'm wondering if it doesn't make more sense to use a global variable/schema like @ravwojdyla proposed in https://github.com/pystatgen/sgkit/pull/124#issuecomment-679089416 to create and validate individual DataArrays rather than a function that creates a whole Dataset.  The vcf reader code would then look like:

```python
from sgkit import variables, attrs
call_genotype = np.empty(...)
# ... VCF Extraction logic ...
call_genotype: DataArray = variables.call_genotype.array(call_genotype, mixed_ploidy=True) 
# assert call_genotype.attrs['mixed_ploidy']
data_vars = [
    variables.variant_contig.array(variant_contig), # Does validation and conversion to DataArray
    variables.variant_position.array(variant_position),
    ...
    call_genotype,
    variables.call_genotype.mask(call_genotype), # create "call_genotype_mask" (has mixed_ploidy attr)
    variables.call_genotype.non_alleles(call_genotype), # create "call_genotype_non_allele" (has mixed_ploidy attr)
    # Other VCF fields we haven't imported but will probably want to eventually:
    variables.allele_depth.array(allele_depth),
    variables.genotype_quality.array(genotype_quality),
    ...
]
ds = xr.Dataset(
    data_vars={v.name: v for v in data_vars}, 
    attrs=attrs(variant_contig_names)
)
```

What do you think of that @tomwhite / @ravwojdyla?  This would make it possible for a user to provide a list of variables to extract from VCF without us needing to wire them up in a `create_*` function.  It would also obviate the need for the clunky variable additions that the plink and vcf readers all have now (and that the bgen reader should have if it respected the sample metadata) after the main dataset is created.

**Comment by tomwhite** [comment]
+1 to creating datasets directly in the VCF code (without using `create_genotype_call_dataset`).

**Comment by timothymillar** [comment]
> Do you already know how cyvcf2 distinguishes between non-alleles and missing alleles (if at all)?

It seems to be a little inconsistent as some parts of the API to handle mixed ploidy (second variant above):

```
>>> variant.genotypes
[[0, 0, 0, 0, False], [0, 1, False], [0, 1, -1, -1, False]]
```

But the call used in the vcf_reader code doesn't (second row should be diploid):

```
>>> variant.genotype.array()
array([[ 0,  0,  0,  0,  0],
       [ 0,  1, -1, -1,  0],
       [ 0,  1, -1, -1,  0]], dtype=int16)
```

I'll look into the cyvcf2 code a bit more, might require a PR over there...

The BCF spec does define a missing (non-allele) value for this purpose. So it should just be a matter of decoding that value to something sensible.

**Comment by timothymillar** [comment]
I've opened a [cyvcf2 issue](https://github.com/brentp/cyvcf2/issues/169).

**Comment by timothymillar** [comment]
cyvcf2 v-0.20.8 now supports mixed ploidy in `Genotype.array()` also using `-2` to indicate non-alleles.

I have a very basic implementation of `vcf_to_zarr_sequential` that supports mixed ploidy.
This requires the user to specify a maximum ploidy and will truncate genotypes if they exceed this maximum.
I think this is the most practical way to go, probably throwing a warning if a genotype is truncated.

It looks like this should probably wait on #258

**Comment by tomwhite** [comment]
That sounds great @timothymillar. I've just submitted #289, so the VCF migration should hopefully be done before too long.

BTW I had to make a [small change](https://github.com/pystatgen/sgkit/pull/289/commits/12daba960ac407744b4a190f879304dd0ff70b7e) to a test due to the mixed ploidy change, which shows that your change has been picked up!

**Comment by tomwhite** [comment]
This was done in #373
