### ISSUE TITLE
Git merge strategy - disable merge commits?

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#26]
I would like to suggest to disable merge commits for PRs and essentially enforce rebase/squash only - the advantage of this strategy is that the git (graph) history is a lot cleaner. Would that be fine with everyone?

**Comment by jeromekelleher** [comment]
Merge commits make the history a bit more readable, IMO so I'd be mild -1. We tried out the "force linear history" thing on GitHub for a bit and ended up reverting.

Have you considered using [mergify](https://mergify.io/) instead? You can set this up to automatically rebase, rerun CI and then merge if it passes. It was life changing for me, I love it!

**Comment by eric-czech** [comment]
+1 to mergify instead

**Comment by ravwojdyla** [comment]
@jeromekelleher in this issue I don't worry about automation (`mergify`), just the git history. I have been working with "linear history", and just prefer that for cleaner history and easier rebasing. I see `mergify` as an orthogonal question, we could use `mergify` with rebase/squash only method, right?

**Comment by jeromekelleher** [comment]
So I totally agree with having a linear history. I've just found that having "squash" commits from the GitHub interface isn't actually that helpful as 

a. You lose the merge commit that serves as a summary of the commits that went into a PR (and it's a bit too strict to day all PRs must be squashed down to one commit - that's not how you get to a clear history, IMO). You also lose the nice branchy view of history on the GitHub UI, which gives a good sense of who did what, when.
b. You still have to get people to rebase before you click the "merge/squash/whatever" button on GitHub, because the CI they have run might be out of date. (GitHub just checks for merge conflicts).

Mergify takes the drudgery out of this, and lets you keep a nice linear Git history, and means you have to ask contributors to rebase a *lot* less.

**Comment by ravwojdyla** [comment]
@jeromekelleher yea, I see. So I'm +1 `mergify` but that is separate question :)

So to be clear, there are really 3 options regarding merge strategy (all of which are supported by `mergify`):
1. merge: we keep all the separate commits from the PR via merge commit -> branch in git graph and non-linear history
2. rebase: we keep all the separate commits from the PR via rebase -> linear history
3. squash: we get a single squashed commit per PR -> linear history

In this issue I'm advocating specifically to avoid `merge` and instead use `rebase` (or `squash` if people prefer that one, though it's a bit against git/linux philosophy). So we still keep each commit, keep linear history (making it easier to use git bisect for example).

**Comment by jeromekelleher** [comment]
Ah, I see, I misunderstood. I like (1), but with the various merge commits going in linearly. So, things branch off, but they join back in before anything else splits/merges. It doesn't matter that much though.

**Comment by ravwojdyla** [comment]
To sum up the discussion from the weekly call:
 * if we can encode all the rules we need for PR, we want to use mergify
 * we want to keep linear history, and if mergify can do that with `merge` strategy (which sth we need to validate) then we can do that otherwise we switch to `rebase`

Will keep this open until it's all configured.

**Comment by hammer** [comment]
Now that #82 is in, do we want to add some content to our contributing docs about our git merge strategy?

**Comment by ravwojdyla** [comment]
Merge commit strategy is no more. I have requested to install `mergify` so the owner(s) will probably get that request, until then we have `rebase` and `squash` strategies.

**Comment by ravwojdyla** [comment]
I will close this issue, and create a separate one for `mergify`.

**Comment by eric-czech** [comment]
@ravwojdyla did you do it in the other repos too?  What did you change and how does one check it?

**Comment by ravwojdyla** [comment]
@eric-czech just this repo, in repo `Settings` there is `Merge button` section.
