### ISSUE TITLE
LD-prune implementation

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#31]
The prototype LD-prune implementation at [gwas-analysis/lib/method/core.py](https://github.com/related-sciences/gwas-analysis/blob/master/notebooks/platform/xarray/lib/method/core.py#L13) extends [skallel.locate_unlinked](https://scikit-allel.readthedocs.io/en/stable/stats/ld.html?highlight=locate_unlinked#allel.locate_unlinked) to be parallelizable by dask, runnable on GPU or CPU, and also adds support for windowing based on genomic distance (it is equivalent for fixed-size windows/steps).

This could be moved over as-is or it may be worth discussing some of the aspects of the implementation first.  

Either way, we should wait on resolutions to https://github.com/pystatgen/sgkit/issues/3 and https://github.com/pystatgen/sgkit/issues/29 so we know what target API to refactor towards.

**Comment by jeromekelleher** [comment]
Can potentially use tskit's [ld calculator](https://tskit.readthedocs.io/en/latest/tutorial.html#calculating-ld) for validation of LD computations. The API is quite old and a bit limited, though. We're working on extending the functionality, but it'll be a while before it's ready.

**Comment by eric-czech** [comment]
I was planning to start adding in pieces of this soon, and I wanted to better explain my plan for that first.

The prototype versions of this I had written reduce LD pruning into three separate problems, each of which I know are usable in at least one other context as well:

1. Determining what variants are included in windows for comparison
    - This is very similar to [hal.locus_windows](https://hail.is/docs/0.2/linalg/utils/index.html#hail.linalg.utils.locus_windows) except that I'm also computing similar windows that correspond to chunks rather than individual variants
    - This requires that all of the window definitions for a single contig fit in memory

2. Computing a sparse LD matrix
    - This becomes straightforward once the windows are defined and I had lifted [scikit_allele.rogers_huff_r](https://scikit-allel.readthedocs.io/en/stable/stats/ld.html#allel.rogers_huff_r) verbatim to do it
    - @jeromekelleher/@alimanfoo  do you know if there are any important differences between the tskit r2 calculation and the one in scikit-allel?
    - This requires that chunking for genotypes is only along one axis
      - The solution discussed [here on the Dask discourse](https://dask.discourse.group/t/creating-sparse-output-from-dense-inputs-to-matrix-multiplication/26) would be much better (and much more difficult)
3. Finding a maximal independent set (MIS) between variants with LD over a threshold
    - I implemented what Chris Chang described for PLINK [here](https://groups.google.com/d/msg/plink2-users/w5TuZo2fgsQ/WbNnE16_xDIJ) after my head stopped spinning from trying to understand it in [plink-ng/1.9/plink_ld.c](https://github.com/chrchang/plink-ng/blob/master/1.9/plink_ld.c)
   - This is equivalent to scikit-allel [locate_unlinked](https://scikit-allel.readthedocs.io/en/stable/stats/ld.html?highlight=locate_unlinked#allel.locate_unlinked) for certain parameterizations 
     - My unit testing plan centers around getting a lot of coverage by asserting equality with this for many inputs
   - This requires that all of the pairwise variant indexes (above the LD threshold) for a contig fit in memory

The biggest scalability limitation for this in the very last bullet point.  The pairwise entries don't really need to fit in memory, they just need to be processed sequentially and I'm sure there's some reasonable way to do that with Dask. 

I thought this was all complicated enough that it warranted a pretty diagram, so here's a summary of what I'm proposing:

![Screen Shot 2020-08-10 at 8 24 32 AM](https://user-images.githubusercontent.com/6130352/89782313-0a180880-dae3-11ea-84d7-27b6db62aeb9.png)

**Comment by eric-czech** [comment]
In https://github.com/dask/dask/issues/6835#issuecomment-729866844, @RogerMoens mentioned matrix sketching and in a quick read of that [paper](https://www.cs.yale.edu/homes/el327/papers/simpleMatrixSketching.pdf), I saw this:

> The third sketching approach is to find a small subset of matrix rows (or columns) that approximate the entire matrix. This problem is known as the Column Subset Selection Problem and has been thoroughly investigated, [16][12][6][11][14][5] 

We should see if any of those references are relevant here.

**Comment by tomwhite** [comment]
I've been thinking about the implementation of LD-prune and how it relates to the [windowing support](https://pystatgen.github.io/sgkit/latest/generated/sgkit.window.html) we have in sgkit.

The terminology here is potentially confusing. In gwas-analysis code the `axis_intervals` function returns _axes_ and _chunks_. A _chunk_ in that context is _not_ a  Dask chunk, and is what we have been calling a _window_ in sgkit, which is a contiguous range of variants from a start index (inclusive) to a stop index (exclusive).

Note also that `axis_intervals` uses a variant-centric approach to finding windows/chunks - i.e. each range starts at a variant, rather than at a multiple of the window size (or step). Currently, sgkit's `window` function only supports defining fixed-sized windows in "index" space (not "position" space). However, the computed windows result in an arbitrary set of window start and stop indexes - which are a very general way of representing windows - so in principle any way of defining windows would work with this underlying representation. This means we could add functions to define windows in "position" space, and using a variant-centric approach (locus windows); see #341.

The functions for computing a sparse LD matrix and finding a maximal independent set (steps 2. and 3. from above) translate fairly directly from the gwas-analysis code. For the LD matrix, I think the computation can be carried out from the set of window definitions (or chunks in gwas-analysis terminology), by iterating over pairs of variants in a window - i.e. the axis intervals are not needed - but please let me know if I am missing something @eric-czech.

There are some choices of representation that we might do differently from the original gwas-analysis code, which tends to favour Dask dataframes over Xarray Datasets (for example). It's probably worth making these more consistent with existing sgkit functions.

**Comment by tomwhite** [comment]
Fixed in #561.
