### ISSUE TITLE
Installation issues with cyvcf2 on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#327]
I was trying to install this on Ubuntu 16.04

```
pip install -r requirements.txt -r requirements-dev.txt -r requirements-doc.txt
```

I got the following issues:

### 1. curl.h missing

```
    htslib/hfile_s3_write.c:86:23: fatal error: curl/curl.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```

This was fixed with: (we install this in CI)
```
sudo apt install -y libcurl4-openssl-dev
```

### 2. bzlib.h missing
```
...
    htslib/cram/cram_io.c:53:19: fatal error: bzlib.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```

This was fixed with:
```
sudo apt-get install libbz2-dev
```

Then this:

### 3. lzma.h missing
```
...
    htslib/cram/cram_io.c:57:18: fatal error: lzma.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```

This was fixed with:

```
apt-get install liblzma-dev
```

I guess, we don't see this in the CI, because these are already present, also we have Ubuntu 18.04 in the CI:

<img width="630" alt="Screenshot 2020-10-15 at 13 22 54" src="https://user-images.githubusercontent.com/5647941/96116922-8bc45200-0ee9-11eb-9817-0bb41ec5c069.png">

Although these are linux specific, I think, we can probably worth mentioning these in the docs and also we install libcurl4-openssl-dev in the CI:
https://github.com/pystatgen/sgkit/blob/162447e20e6b680f35730047f0d28a7064d079bc/.github/workflows/build.yml#L22

its not mentioned in the contributing docs either: https://pystatgen.github.io/sgkit/contributing.html#install

**Comment by hammer** [comment]
@horta let's continue the discussion of the `cyvcf2` wheels on this issue.

As noted on https://github.com/brentp/cyvcf2/pull/175#issuecomment-723499776, and as we discussed briefly prior to the work being done, we'll need to link SSL statically in the curl build used by htslib if we want remote reads to work with wheels.

Given that reading from GCS is a primary use case for us and the security issues caused by using a statically linked ssl library for this project are low, my inclination would be to just link SSL statically to allow for an easier installation for our users.

I'd love to hear what others think though!

**Comment by jeromekelleher** [comment]
> Given that reading from GCS is a primary use case for us and the security issues caused by using a statically linked ssl library for this project are low, my inclination would be to just link SSL statically to allow for an easier installation for our users.

100% - linking statically is very much the philosophy of binary wheels anyway.

**Comment by horta** [comment]
Sounds reasonable. I will work on that tomorrow (Tuesday) =)

**Comment by horta** [comment]
@jeromekelleher is correct in that cibuildwheel already takes care of that. In fact, libss, libcurl, alongside with htslib are included in the wheels. I've just updated the issue https://github.com/brentp/cyvcf2/pull/175 with some findings and (it seems so) the solution.

**Comment by jeromekelleher** [comment]
That's great news @horta! Just so I'm clear where we got to, there's still an issue on Linux systems where there is an existing installation of OpenSSL with a different version to the one we compiled against? I wonder if this is because htslib uses a plugin system rather than actually linking, and if perhaps we could influence the search order for htslib's plugins to make this robust?(but maybe this is a discussion we should have over on the cyvcf2 repo)

**Comment by horta** [comment]
Right now cyvcf2 wheel is being built against ssl 1.1.x on Linux (although the wheels are not in test pypi yet, explained in the above link), which should work in machines with both 1.0.x and 1.1.x as far as I tested. So the problem is not exactly the difference in ssl version but linking it against deprecated ssl 1.0.x version (I think Python 3.5 dropped its support of ssl 1.0.x).

In summary, the problem seems to be solved, I just can't try it on Travis CI because I have no OSS credits anymore for this month.

**Comment by hammer** [comment]
@aktech can you confirm you no longer have this issue now that there are `cyvcf2` wheels?

**Comment by aktech** [comment]
Yes, it works for me now.
