### ISSUE TITLE
Fix mypy continuous integration issues

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#39]
From https://github.com/pystatgen/sgkit/pull/32:

- [x] [mypy precommit](https://github.com/pre-commit/mirrors-mypy) should use the settings in `setup.cfg`
- [ ] GH actions should publish the mypy HTML report (cf. [Publishing Test Results](https://github.community/t/publishing-test-results/16215) on the GitHub community Discourse).
- [ ] precommit mypy hook requires duplication of requirements

**Comment by hammer** [comment]
@tomwhite should we file an upstream issue to inquire about making precommit use `setup.cfg`? It appears that https://github.com/asottile is the person who would know best so we could also just ask him directly.

**Comment by tomwhite** [comment]
Opened https://github.com/pre-commit/mirrors-mypy/issues/22

**Comment by ravwojdyla** [comment]
precommit + mypy fixed in #47, I've opened pre-commit/mirrors-mypy#23

**Comment by hammer** [comment]
Do we want to adopt the workaround from https://github.com/pre-commit/pre-commit/pull/880#issuecomment-633284290?

**Comment by ravwojdyla** [comment]
@hammer yea - looks like we gonna have to script it, should not be too hard, but since we have multiple repos, probably makes sense to build it as a precommit hook so it can be reused (+ open source for others). I don't think this is time sensitive, nevertheless would be good to have. I image it would be a simple check that parses requirements file and precommit config and fails if not in sync.

**Comment by tomwhite** [comment]
No longer relevant as we're not currently using mypy.
