### ISSUE TITLE
Add docs for variables to xarray attributes

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#393]
It would be nice if the doc strings for sgkit variables appeared in the xarray variable metadata. Users would be able to inspect this information when looking at datasets in notebooks. As an example, have a look at this [Pangeo dataset](https://catalog.pangeo.io/browse/master/ocean/sea_surface_height/) - try clicking on the document icon for a data variable (e.g. `adt`).

![pangeo](https://user-images.githubusercontent.com/85085/99687746-e9196900-2a7c-11eb-9f4a-d5deec8aa9a3.png)

Unfortunately, I can't see an easy way of doing this, since the `__doc__` attribute for sgkit variables is for the `ArrayLikeSpec` class, not for the variable instance itself. This is regular Python semantics, and the reason that the docs have the correct descriptions is because Sphinx is [reading them itself](https://www.sphinx-doc.org/en/1.4.8/ext/autodoc.html#directive-autoattribute).

@ravwojdyla any thoughts on how to do this?

**Comment by ravwojdyla** [comment]
Good idea @tomwhite! Thinking about this, 2 ideas come to my mind:

1. move the docstring into the ctor of the `ArrayLikeSpec`, and assign `__doc__` on the instance. Since those variable declarations are module level variables they get instantiated at the module import, thus Sphinx would be able to properly fetch doc strings. Now we would need to populate datasets with the extra doc available in the `ArrayLikeSpec` instances, we could modify `validate` or add another method for that.

2. alternatively we could keep the current syntax of docstring on the variables and use `inspect` module to get the line of variable declaration and fetch any docstring that follows it.

Right now, I lean towards 1st option more. wdyt?

**Comment by tomwhite** [comment]
I agree the first option sounds preferable.
