### ISSUE TITLE
Tools for enforcing coding standards

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#5]
Which tools should we use for enforcing coding standards?

Here is a table summarising what (related projects) [Zarr](https://zarr.readthedocs.io/en/stable/contributing.html#code-standards), [Dask](https://docs.dask.org/en/latest/develop.html#code-formatting), and [Xarray](https://xarray.pydata.org/en/latest/contributing.html#contributing-to-the-code-base) use.

| |Zarr|Dask|Xarray|
|-|----|----|------|
|Formatting|-|Black|Black|
|Linting|Flake8|Flake8|Flake8|
|Imports|-|-|isort|
|Type checking|-|-|Mypy|
|Code coverage|Coveralls|Coveralls|Codecov|
|CI|Travis|Travis|Azure Pipelines|

I would like to propose we use:
* [Black](https://black.readthedocs.io/en/stable/)
* [Flake8](https://flake8.pycqa.org/en/latest/)
* [isort](https://timothycrosley.github.io/isort/)
* [Mypy](https://mypy.readthedocs.io/en/stable/)
* [Coveralls](https://coveralls.io/)
* [GitHub Actions](https://help.github.com/en/actions)

GitHub Actions is the only one that isn't used by any of the three other related projects, but it seems to be a popular choice for new projects due to its close integration with GitHub.

**Comment by hammer** [comment]
I decided to learn a bit more about Codecov vs. Coveralls. Based on zero experiences with either product I would vote for Codecov, mostly because it's nearly standard across Python projects, to the point that I wonder how Dask and Zarr ended up with Coveralls!

- Coveralls is developed by [Lemur Heavy Industries](http://lemurheavy.com/), which appears to be a small consulting shop in LA. One of the founders, amusingly, appears to have been the guitarist for Capital Cities, whose [song](https://www.youtube.com/watch?v=47dtFZ8CFo8) "Safe and Sound" you've surely heard.
- Codecov is developed by a company called [Codecov](https://codecov.io/) with a CEO is in SF and CTO in Nashville.
- A brief [discussion](https://discourse.julialang.org/t/codecov-vs-coverall/27595) in the Julia community favored Codecov. [Merging reports](https://docs.codecov.io/docs/merging-reports) was cited as a feature in Codecov but not in Coveralls.
- Codecov is used by [CPython](https://codecov.io/gh/python/cpython), [NumPy](https://codecov.io/gh/numpy/numpy), [Pandas](https://codecov.io/gh/pandas-dev/pandas), [Arrow](https://codecov.io/gh/apache/arrow), [sklearn](https://codecov.io/github/scikit-learn/scikit-learn), [matplotlib](https://codecov.io/github/matplotlib/matplotlib), and [Seaborn](https://codecov.io/gh/mwaskom/seaborn).

**Comment by jeromekelleher** [comment]
This sounds good @tomwhite. One thing I'd add is it would be nice to use [pre-commit](https://pre-commit.com/) to formalise the requirements. We've been using it for tskit for a while (config [here](
https://github.com/tskit-dev/tskit/blob/master/.pre-commit-config.yaml)) and it's been great.

Black is essential IMO - I've been using it for a few months and it's a revelation. When I think of all the time I've wasted on pointless style discussions on GitHub threads...

**Comment by jeromekelleher** [comment]
Codecov is "fine" IMO @hammer - I wouldn't endorse it too enthusiastically, but it mostly does what it's supposed to.

**Comment by tomwhite** [comment]
Thanks for pointing out pre-commit, @jeromekelleher, I'll take a look.

I agree about using Black - you just let it do all the formatting work and stop thinking about it. Using an IDE plugin is a good idea too.

I'm fine using Codecov too.

**Comment by tomwhite** [comment]
Closing this since we've got all of these tools working now, except code coverage (see #20).
