### ISSUE TITLE
Problem with Tajimas D tests

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#523]
Since #521 the Tajima's D tests have been skipped. We were getting different values > n=2.

**Comment by tomwhite** [comment]
Continuing the discussion from https://github.com/pystatgen/sgkit/pull/521#issuecomment-823405576. For n=10, this change

```
diff --git a/sgkit/tests/test_popgen.py b/sgkit/tests/test_popgen.py
index a5a9f9a..de27946 100644
--- a/sgkit/tests/test_popgen.py
+++ b/sgkit/tests/test_popgen.py
@@ -349,9 +349,12 @@ def test_Fst__windowed(sample_size, n_cohorts, chunks):
 
 # Skipping values > 2, because of this issue:
 # https://github.com/pystatgen/sgkit/issues/522
-@pytest.mark.parametrize("sample_size", [2])
+@pytest.mark.parametrize("sample_size", [10])
 def test_Tajimas_D(sample_size):
     ts = simulate_ts(sample_size)
+    print()
+    print(ts)
+    print("segregating_sites", ts.segregating_sites(span_normalise=False))
     ds = ts_to_dataset(ts)  # type: ignore[no-untyped-call]
     ds, subsets = add_cohorts(ds, ts, cohort_key_names=None)  # type: ignore[no-untyped-call]
     n_variants = ds.dims["variants"]
```
prints
```
╔═══════════════════════╗
║TreeSequence           ║
╠═══════════════╤═══════╣
║Trees          │      7║
╟───────────────┼───────╢
║Sequence Length│  100.0║
╟───────────────┼───────╢
║Sample Nodes   │     10║
╟───────────────┼───────╢
║Total Size     │5.5 KiB║
╚═══════════════╧═══════╝
╔═══════════╤════╤══════════╤════════════╗
║Table      │Rows│Size      │Has Metadata║
╠═══════════╪════╪══════════╪════════════╣
║Edges      │  36│1012 Bytes│          No║
╟───────────┼────┼──────────┼────────────╢
║Individuals│  10│ 172 Bytes│          No║
╟───────────┼────┼──────────┼────────────╢
║Migrations │   0│   4 Bytes│          No║
╟───────────┼────┼──────────┼────────────╢
║Mutations  │  36│   1.0 KiB│          No║
╟───────────┼────┼──────────┼────────────╢
║Nodes      │  23│ 556 Bytes│          No║
╟───────────┼────┼──────────┼────────────╢
║Populations│   1│ 216 Bytes│         Yes║
╟───────────┼────┼──────────┼────────────╢
║Provenances│   2│   1.8 KiB│          No║
╟───────────┼────┼──────────┼────────────╢
║Sites      │  29│ 501 Bytes│          No║
╚═══════════╧════╧══════════╧════════════╝

segregating_sites 31.0
```

The implementation of `Tajimas_D` in sgkit calculates the number of segregating sites as 28 (one of the 29 is not segregating, since it's all ref). If I manually change the number to 31, then the test passes - which shows that it's only this part of the calculation that is causing the discrepancy.

@jeromekelleher does it make sense for the number of segregating sites (31) to be larger than the number of sites (29)?!

**Comment by jeromekelleher** [comment]
Ah! Well, this is interesting. The definition of the ``segregating_sites`` stat is subtle in tskit:

> The sum over sites of the number of alleles found in A at each site minus one, per unit of chromosome length. If all sites have at most two alleles, this is the density of sites that are polymorphic in A. To get the number of segregating minor alleles per window, pass span_normalise=False.

However, we have triallelic sites in this example, which leads to this counter-intuitive result of having 31 segregating sites out of 29!

@petrelharp, do we have the correct definition of Tajima's D in tskit?

**Comment by jeromekelleher** [comment]
Thanks for tracking this down btw @tomwhite, I'd have spent ages figuring that out!

**Comment by tomwhite** [comment]
Ah, interesting. BTW the allele counts are as follows:

```
[[ 7  3  0]
 [ 7  3  0]
 [ 3  7  0]
 [ 7  3  0]
 [ 3  7  0]
 [ 3  7  0]
 [ 4  3  3]
 [ 7  3  0]
 [ 7  3  0]
 [ 3  7  0]
 [ 3  7  0]
 [ 3  7  0]
 [ 7  3  0]
 [ 3  0  7]
 [ 7  3  0]
 [ 7  3  0]
 [ 7  0  3]
 [ 7  3  0]
 [ 7  3  0]
 [ 7  3  0]
 [ 4  3  3]
 [ 9  1  0]
 [ 6  4  0]
 [ 7  3  0]
 [10  0  0]
 [ 9  1  0]
 [ 7  2  1]
 [ 7  3  0]
 [ 3  7  0]]
```

There is one site with 1 allele (`10 0 0`), 25 sites with 2 alleles, and three sites with 3 alleles. So that makes 25*(2-1) + 3*(3-1) = 31 segregating sites, which is what tskit calculates.

**Comment by tomwhite** [comment]
This is the fix to make sgkit agree with tskit (although it should have a better comment!):
```
diff --git a/sgkit/stats/popgen.py b/sgkit/stats/popgen.py
index b430658..f024de9 100644
--- a/sgkit/stats/popgen.py
+++ b/sgkit/stats/popgen.py
@@ -555,7 +555,7 @@ def Tajimas_D(
     ac = ds[variant_allele_count]
 
     # count segregating
-    S = ((ac > 0).sum(axis=1) > 1).sum()
+    S = ((ac > 0).sum(axis=1) - 1).sum()
 
     # assume number of chromosomes sampled is constant for all variants
     # NOTE: even tho ac has dtype uint, we promote the sum to float
```

**Comment by petrelharp** [comment]
As far as I know, there's no canonical definition of Tajima's D with multiallelic sites. The motivation for Tajima's D is based on Watterson's theta:
![Screenshot from 2021-04-22 10-06-05](https://user-images.githubusercontent.com/1046249/115756311-ee901d80-a352-11eb-9950-5bd6f956dfc4.png)
and [Watterson's calculations](https://www.sciencedirect.com/science/article/pii/0040580975900209) assume an infinite-sites model:
![Screenshot from 2021-04-22 10-08-48](https://user-images.githubusercontent.com/1046249/115756369-ff409380-a352-11eb-8032-2e489beea842.png)

Ideally, the value we'd stick in for "segregating sites" is the number of distinct *mutations* that have occurred in the tree, since that's what the infintie sites model assumes - that you can "see" every mutation. We can't do that, because we need something calculable from the genotypes, but what we're using in tskit (number of distinct alleles minus one) is closer to it than just the literal number of segregating sites.

So - yes, I think we are calculating the "right" thing?

**Comment by jeromekelleher** [comment]
Good enough for me, thanks @petrelharp!
