### ISSUE TITLE
GPU CI build not working

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#611]
#567 was merged, but the [GPU build failed](https://github.com/pystatgen/sgkit/actions/runs/946398744): 

> build (3.7)
No runner matching the specified labels was found: self-hosted, gpu

@aktech what kind of observability does cirun support? Any pointers?

**Comment by aktech** [comment]
I just looked at the sgkit's GCP Logs, the error was: `"message": "ZONE_RESOURCE_POOL_EXHAUSTED"`

Which means the zone does not have enough resources (GPUs) available to fulfill the request.

More here: https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation#resource_availability

I am working on making it more resilient so that one can specify multiple regions to search for GPUs, until then the only solution is to try triggering the workflow again.

**Comment by aktech** [comment]
So, as a follow up, can you re trigger the workflow manually to see if there is enough resources now?

(Also, note that if the build gets queued for too long like > 10 min, then also there are so runners to run the workflow on for the same reason mentioned above.)

**Comment by ravwojdyla** [comment]
@aktech retriggered here: https://github.com/pystatgen/sgkit/actions/runs/946398744

**Comment by aktech** [comment]
Thanks @ravwojdyla The GPU tests ran now, they fail at the moment. I have created a separate issue for the same: https://github.com/pystatgen/sgkit/issues/612

**Comment by ravwojdyla** [comment]
@aktech ok, thanks, closing this. For future, if the GPU CI doesn't run, we need to manually retrigger it, right?

**Comment by aktech** [comment]
> @aktech ok, thanks, closing this. For future, if the GPU CI doesn't run, we need to manually retrigger it, right?

Yep
