### ISSUE TITLE
Provide progress bar for `vcf_to_zarr`

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#687]
When converting large VCF files with `vcf_to_zarr`, it would be nice to display a progress bar to users.

**Comment by hammer** [comment]
We could use [nested progress bars](https://github.com/tqdm/tqdm#nested-progress-bars) when running in parallel?

**Comment by jeromekelleher** [comment]
I don't think we should add this to our API since (AFAIK) we can use [Dask's](https://docs.dask.org/en/latest/diagnostics-local.html#progress-bar) methods, and we should be encouraging users to use Dask resources for tracking progress/profiling than trying to wrap this ourselves. See https://github.com/pystatgen/sgkit/issues/48#issuecomment-668576318 for previous discussion of this.

I totally agree that a CLI should have a progress option, though.

**Comment by tomwhite** [comment]
We could document how to use Dask's progress bars with `vcf_to_zarr`.

**Comment by hammer** [comment]
So I tried

```
from dask.diagnostics import ProgressBar
with ProgressBar():
    vcf_to_zarr("1kg.vcf.bgz", "1kg.zarr", max_alt_alleles=1,
              fields=["FORMAT/GT", "FORMAT/DP", "FORMAT/GQ", "FORMAT/AD"],
              field_defs={"FORMAT/AD": {"Number": "R"}})
```

which did not bring up any progress bars. Is there some sort of trick I need to push the ProgressBar into the function call?

Relatedly, I've noticed that when I use this pattern with library functions that contain multiple Dask computations it's hard to figure out which task is having its progress displayed.

I think it might be better to just have a verbose mode for our IO methods, as that way we can set some additional context in our use of progress bars and log messages.

**Comment by jeromekelleher** [comment]
> I think it might be better to just have a verbose mode for our IO methods, as that way we can set some additional context in our use of progress bars and log messages.

Some proper logging would be very helpful I think, and will be essential over time. We could then document how to set up logging conveniently using (e.g.) [daiquiri](https://daiquiri.readthedocs.io/en/latest/).

@tomwhite any thoughts on adding ``logger.debug(...)`` messages to the codebase? Maybe we should fork this out into a separate discussion, so we can make some high-level decisions about how to do logging?

**Comment by tomwhite** [comment]
> which did not bring up any progress bars. I believe Dask is being invoked since the Dataset returned by this call has multiple chunks, so I'm a bit confused as to why the progress bars don't come up.

When the input VCF is small enough, the [sequential](https://github.com/pystatgen/sgkit/blob/d3b77ed878ce421c9363b948a9796f46572fa44a/sgkit/io/vcf/vcf_reader.py#L912) code path in `vcf_to_zarr` is chosen (since it's a single file, and `regions` is None). This path does not use Dask (even though the output Zarr may have multiple chunks), so the progress bar is not displayed.

Your second example shows a progress bar because it's using the parallel code path, which does use Dask.

Would it be possible to have a finer-level of granularity for the sequential case? Not easily. For one thing, we don't know the number of records that a call to `vcf_to_zarr_sequential` is going to read (whether it's a whole VCF file, or a region, as happens in the parallel case), so it would be hard to come up with a good estimate. Also, Dask's concept of progress is at the task level - there's no way to update progress at a finer-level of granularity (as far as I know) - so to use Dask progress we'd have to think about how to break the sequential part into smaller tasks. Again the problem here is that we don't know how many there would be up front.

**Comment by tomwhite** [comment]
> Maybe we should fork this out into a separate discussion, so we can make some high-level decisions about how to do logging?

Yes, this would be very useful!

**Comment by tomwhite** [comment]
Hmm just found https://github.com/tqdm/tqdm#dask-integration. Also, I wonder if we can use file position within the VCF file or region as a rough proxy for progress...

**Comment by benjeffery** [comment]
Just adding my two cents here. I've not missed this at all, as for any substantial dask operation I have the dask dashboard open, which gives me all the progress and task info I need.
I can see that for smaller, local conversions this might be nice and we should signpost the dask context managers that do that.

**Comment by hammer** [comment]
I'm going to close this based on the feedback that the Dask dashboard is sufficient.
