### ISSUE TITLE
cirun not shutting down GCE instances

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#821]
Hey @aktech, I noticed that cirun keeps spinning up GCE instances (w/ GPUs) and then they just hang there without ever being shutdown.  How can we ensure that stops happening, since it's a non-negligible cost when they're up for days like this?

**Comment by aktech** [comment]
Hey @eric-czech thanks for raising this, do you recall the name of the instance, that was not shutdown?

Cirun, shuts down instance, right after the job is completed and also as a extra check it checks for instance lying around every few minutes. The case you have seen might be a one off, when the instance was created but was reported as failed by the GCP API, it's a rare instance, but do happens. Let me know if you see that again before deleting it.

**Comment by eric-czech** [comment]
I see.  I caught it once before last month where an instance was up idling for ~10 days.  This time I actually say 3 separate instances that had been up for ~2 days, so it didn't seem like a one-off.  I'll keep a closer watch on it now and suspend them instead. 

Can you not see logs related to how sgkit instances were managed in the last month or two though?

**Comment by aktech** [comment]
>This time I actually say 3 separate instances that had been up for ~2 days,

This is basically, for each build. Every build spuns up 3 instances. There might have been unregistered, some times when the  GCP's API doesn't returns success and creates an instance.

> Can you not see logs related to how sgkit instances were managed in the last month or two though?

I didn't see anything unusual, but will take a closer look.

**Comment by ravwojdyla** [comment]
@aktech looking at the logs I believe there is a couple of issues here. Let's take a look at the last GPU action: https://github.com/pystatgen/sgkit/actions/runs/1805609747, based on your last comment, this should create 3 VMs. From the logs it seems like cirun tried to create 14 VMs and succeeded to create 9 VMs, cleaned up only 6 of them, the rest was deleted by Eric. Details:

```
us-central1-b/cirun-pystatgen--sgkit-0bea2e4  # was created and used for py3.8 build
us-central1-b/cirun-pystatgen--sgkit-b8dee4e  # was created and used for py3.9 build
us-central1-b/cirun-pystatgen--sgkit-d5b61f7  # was created and used for py3.7 build

us-central1-b/cirun-pystatgen--sgkit-31296f6  # Successfully created, unused, deleted at the end of the build
us-central1-b/cirun-pystatgen--sgkit-49e6a41  # Successfully created, unused, deleted at the end of the build
us-central1-b/cirun-pystatgen--sgkit-4f69670  # Successfully created, unused, deleted at the end of the build

us-central1-b/cirun-pystatgen--sgkit-92765d6  # Failed to create due to RESOURCE_OPERATION_RATE_EXCEEDED
us-central1-a/cirun-pystatgen--sgkit-92765d6  # Retried in a different zone, created, deleted by Eric 3 days later

us-central1-b/cirun-pystatgen--sgkit-f806665  # Failed to create due to RESOURCE_OPERATION_RATE_EXCEEDED
us-central1-a/cirun-pystatgen--sgkit-f806665  # Retried in a different zone, created, deleted by Eric 3 days later

us-central1-b/cirun-pystatgen--sgkit-b4d702f  # Failed to create due to QUOTA_EXCEEDED
us-central1-a/cirun-pystatgen--sgkit-b4d702f  # Retried in a different zone, failed to create due to QUOTA_EXCEEDED
us-central1-f/cirun-pystatgen--sgkit-b4d702f  # Retried in a different zone, failed to create due to QUOTA_EXCEEDED
us-east4-b/cirun-pystatgen--sgkit-b4d702f  # Retried in a different zone, created, deleted by Eric 3 days later
```

 Issues:
 * when a VM fails to create, is retried and created in a different zone, it's never deleted. It appears that cirun will only try to delete the VMs in the 1st/org zone (`us-central1-b`) it tried to create the VM, fail and give up, without looking into other zones.
 * too many VMs are created, some of them appear unused - why?
 * the build takes 3mins, but the VMs are up for about 15-20min - why? can we make this shorted?

**Comment by aktech** [comment]
@ravwojdyla Thanks a lot for taking a look at these.

Pulling the database, all the VMs created and for a given workflow (for reference):

| name                           | created_at               | url                                                                       | region        | state      |
| ------------------------------ | ------------------------ | ------------------------------------------------------------------------- | ------------- | ---------- |
| cirun-pystatgen--sgkit-31296f6 | 2022-02-07T09:31:06.095Z | [5090800336](https://github.com/pystatgen/sgkit/runs/5090800336?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-d5b61f7 | 2022-02-07T09:30:01.234Z | [5090800336](https://github.com/pystatgen/sgkit/runs/5090800336?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-49e6a41 | 2022-02-07T09:30:32.647Z | [5090800336](https://github.com/pystatgen/sgkit/runs/5090800336?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-4f69670 | 2022-02-07T09:31:07.203Z | [5090800397](https://github.com/pystatgen/sgkit/runs/5090800397?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-b8dee4e | 2022-02-07T09:30:36.385Z | [5090800397](https://github.com/pystatgen/sgkit/runs/5090800397?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-0bea2e4 | 2022-02-07T09:30:05.198Z | [5090800397](https://github.com/pystatgen/sgkit/runs/5090800397?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-b4d702f | 2022-02-07T09:33:37.803Z | [5090800460](https://github.com/pystatgen/sgkit/runs/5090800460?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-92765d6 | 2022-02-07T09:31:40.626Z | [5090800460](https://github.com/pystatgen/sgkit/runs/5090800460?check_suite_focus=true) | us-central1-b | terminated |
| cirun-pystatgen--sgkit-f806665 | 2022-02-07T09:32:37.794Z | [5090800460](https://github.com/pystatgen/sgkit/runs/5090800460?check_suite_focus=true) | us-central1-b | terminated |


> when a VM fails to create, is retried and created in a different zone, it's never deleted. It appears that cirun will only try to delete the VMs in the 1st/org zone (us-central1-b) it tried to create the VM, fail and give up, without looking into other zones.

Seems like this is the **root cause**, our retry mechanism doesn't seem to update the actual region for the given VM (after a change of region during retry), hence the deletion fails. I'll fix this.

> too many VMs are created, some of them appear unused - why?

If you look closely in the logs, there are only 9 VMs created, the 14 you see are repeated ones (i.e. same ID). There are 3 VMs created for each workflow, look at the DB data above.

> the build takes 3mins, but the VMs are up for about 15-20min - why? can we make this shorted?

This was a problem earlier, when we didn't had a way to know job is completed as there wasn't a GitHub webhook with runner details to notify job completion, but they recently introduced a `workflow_job` webhook to handle this issue. I implemented this last week, which mean runners should now be deleted right after the job is completed.

**Comment by ravwojdyla** [comment]
@aktech thanks for a prompt reply! Looking forward to the fixes. There is something I don't understand here tho, regarding: 

>> too many VMs are created, some of them appear unused - why?

> If you look closely in the logs, there are only 9 VMs created, the 14 you see are repeated ones (i.e. same ID). There are 3 VMs created for each workflow, look at the DB data above.

Correct, 9 created, but why 9 VMs for a workflow run with 3 jobs? Correct me if I'm wrong, but the URLs in your tables point to specific jobs in a the same workflow https://github.com/pystatgen/sgkit/actions/runs/1805609747, there should be only 3 jobs - py3.7, py3.9 and py3.9 - right? In fact if you click on those URLs and unroll logs for "Set up job", the VMs won't match for 6 of those links - why? For example the 1st row in the table, the logs say the runner was `cirun-pystatgen--sgkit-d5b61f7`, but your table says `cirun-pystatgen--sgkit-31296f6`. Maybe there's a bug where the count:

https://github.com/pystatgen/sgkit/blob/93af9a26f372c9136694b85727b7f540129f193d/.cirun.yml#L22

actually provisions 3 VMs per **job** not **workflow**?

**Comment by aktech** [comment]
@ravwojdyla @eric-czech All the above mentioned issues, should be fixed now and the `count` parameter in the `.cirun.yml` is no longer required.

**Comment by eric-czech** [comment]
Thanks @aktech!  What ended up being the problem?  The new hook?

**Comment by aktech** [comment]
> What ended up being the problem? The new hook?

The migration to new hook was not done properly, hence I left a couple of bugs. 😅

**Comment by aktech** [comment]
@eric-czech Can we close this issue now? I believe all the concerns are addressed.

**Comment by eric-czech** [comment]
Yep, looks good on our side and we haven't seen any lingering instances.  Thanks for the help @aktech!
