### ISSUE TITLE
Provide tutorial(s) to introduce new users to sgkit

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#88]
Once our data structures and core operations have stabilized and we have put out a release on PyPI, we should provide a tutorial to introduce users to `sgkit`.

Inspirations include @alimanfoo's [A tour of scikit-allel](http://alimanfoo.github.io/2016/06/10/scikit-allel-tour.html), the [Xarray Tutorial](https://xarray-contrib.github.io/xarray-tutorial/), the [Hail GWAS Tutorial](https://hail.is/docs/0.2/tutorials/01-genome-wide-association-study.html), and https://github.com/pystatgen/sgkit/pull/78.

We should also determine if these tutorials should live in this repo or in a separate repo, and if they are best presented at reST or as Jupyter notebooks.

@alimanfoo notes that [Sphinx-Gallery](https://sphinx-gallery.github.io/stable/index.html) is one way to bring notebooks into Sphinx.

**Comment by jerowe** [comment]
A quick note on the notebooks vs rst discussion.

Jupyter notebooks can be [imported into sphinx docs through an extension.](https://nbsphinx.readthedocs.io/en/0.7.1/)

**Comment by jerowe** [comment]
I really do disagree with the whole idea that user docs should be done after. IMO they should be done during the process, and updated as things change. 

Otherwise, they just get thrown in as a not very well done afterthought. Users who are not software engineers, as in almost bioinformatician I know, end up being told "tough luck". 

Write docs early and iterate often!

**Comment by alimanfoo** [comment]
> I really do disagree with the whole idea that user docs should be done after. IMO they should be done during the process, and updated as things change.

Hi @jerowe, FWIW I totally agree. If there has been any suggestion to hold off a little, I think it is just because we are at such an early stage of API design that things may change a lot over the next few weeks. So we might want to hold off putting a lot of energy into tutorial docs just for a short while, until there have been a few more rounds of API discussion.

**Comment by jerowe** [comment]
@alimanfoo I like the suggestion you made possibly yesterday, and I think fits into some of the distinctions @hammer and @eric-czech made about docs. ( Days are a bit fuzzy for me ATM. ;-) ) 

It could be the case that the repo should be the place for technical only docs and to peruse the various statistical methods and what sort of data structure they take. 

Then down the road, there could be a blog type format, like what you did with the PCA posts, that are more case studies and descriptive. An added bonus to this could be that there are already mechanisms in place to more widely distribute blog posts.

**Comment by tomwhite** [comment]
Closed by #463
