### ISSUE TITLE
Replace `inverse_additive_relationships` with `pedigree_inverse_relationship`

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#897]
Similar to #895, depends on #891

The inverse additive relationship matrix (ARM) is a sparse matrix which shouldn't require the full (dense) kinship matrix to be calculated in advance. The inverse ARM can be calculated from the same subset of parental kinships used to calculate the inbreeding coefficient in #891 and this should result in a similar speed up as seen in that PR. 
Currently `inverse_additive_relationships` returns the inverse ARM as a dense matrix, but ideally this would (optionally?) be returned as a sparse matrix. How do others feel about picking up [pydata/sparse](https://sparse.pydata.org/en/stable/) as a dependency?

**Comment by jeromekelleher** [comment]
The [requirements](https://github.com/pydata/sparse/blob/master/requirements.txt) looks like a subset of what we're already pulling in, so that's fine.

I see they are using numba too with a version pin, so there is potential for conflicting requirements.

Assuming no dependency conflicts, I'd see no reason not to use sparse if it's a "hidden" internal detail. However, if we're returning sparse arrays to the user we'd need to think a bit harder about what the implications of that are.

**Comment by timothymillar** [comment]
> if we're returning sparse arrays

That was the intention but it would be simple enough to make dense the default and sparse optional. [Dask supports sparse](https://docs.dask.org/en/latest/array-sparse.html) as does xarray, although there are still some [rough edges](https://github.com/pydata/xarray/discussions/6683).

I guess we could deffer this decision for now by having an internal method that returns arrays of coordinates and values. These are simple to convert to dense or sparse encodings. The exposed API would still return a dense matrix but there is an escape hatch if a sparse encoding is necessary. Or does that sound like an official unofficial API :thinking:.

**Comment by hammer** [comment]
I recall @tomwhite trying out sparse library options when he was working on scanpy: https://github.com/scverse/scanpy/issues/921#issue-522843166. He might have some thoughts?

**Comment by tomwhite** [comment]
> I recall @tomwhite trying out sparse library options when he was working on scanpy: [scverse/scanpy#921 (comment)](https://github.com/scverse/scanpy/issues/921#issue-522843166). He might have some thoughts?

My main thought is that it's not always obvious how to best get chunking and sparsity to play well together. 

As the referenced issue shows, there were some performance issues with pydata sparse, so I ended up writing my own wrapper class. However, since then [sparse array classes](https://docs.scipy.org/doc/scipy/reference/sparse.html#sparse-array-classes) (in contrast to sparse matrices) have been added to scipy, so I would suggest we use those (assuming everything is 2D).

**Comment by timothymillar** [comment]
Thanks, that's a useful reference. AFAICT the scipy.sparse array classes still have issues integrating with dask/xarray. I think it's probably best to stick to dense arrays for now and revisit sparse encodings later if/when there's a clear performance benefit.
