### ISSUE TITLE
VCF export

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#924]
VCF is the bottleneck that essentially all variant data goes through these days, and people will need to export data that they have worked with in sgkit to VCF so that it can be processed with other tools. Not having a solid way of exporting data to a widely used format is a significant missing piece of functionality.

I see three ways we can go about exporting to VCF:

1. Use htslib via a python library that supports writing VCF
2. Write the VCF text directly ourselves using numba
3. Use some numpy tricks to write the text by manipulating numpy arrays.

Both 2 and 3 have the disadvantage that we're writing out uncompressed text, and in practise the user would need to filter this through bgzip for the output to be useful. AFAIK there's no Python interface to bgzip (but, I haven't looked). I don't think this is a show-stopper, though.

I haven't tried using Python VCF writing libraries for a while, but previous experience has shown that they aren't great. I don't think cyvcf2 really supports it, and the only other one I know is PySAM (which I don't think we want another dependency on, and I doubt would scale in the way we want).

Option 2 could be good, but I'm not sure how adapt numba is at generating text. Presumably we could work with numpy int8 arrays which would do the equivalent things and we should be able to get reasonable performance from it.

Option 3 is what we've used in tskit, which gives quite respectable performance (100s of megabytes per second for large numbers of samples). See the code [here](https://github.com/tskit-dev/tskit/blob/a709954e9e4a941850ac9b0d431df4360978d52f/python/tskit/vcf.py#L256). The trick is to pre-allocate the arrays of text, manipulate the bits that change for each row using numpy operations, and then convert the buffer to a string just before outputting.

This works well for tskit, but it's a much more constrained space of VCFs that need to be dealt with (no GL cols, etc) so I'm not sure it would work here (or at least, it wouldn't get excessively complicated).

Any thoughts @tomwhite?

**Comment by tomwhite** [comment]
cyvcf2 does support [writing VCF](https://brentp.github.io/cyvcf2/docstrings.html#cyvcf2.cyvcf2.Writer), including bgzip. 

There is actually already support for [converting sgkit datasets to VCF](https://github.com/pystatgen/sgkit/blob/6554e54d5808ba975d73d84c93976ba807076f3d/sgkit/tests/io/vcf/vcf_writer.py#L131-L201 ), which I wrote a while back for testing purposes. This is Option 1 in your categorisation. (It doesn't do compression, but that would be easy to add.) It works pretty well as the test covers lots of cases for round-tripping VCF.

Of course, the big downside is that it is not parallelized, which was the main reason I marked it as test code originally.

It's probably worth thinking about this more. Could we write "sharded" VCF, so that each shard has the same header, and can be combined using [`bcftools concat --naive`](https://samtools.github.io/bcftools/bcftools.html#concat)?

Or possibly write headerless shards, so they can be concatenated using the filesystem (since bzgip files can be concatenated). (This is what GATK does for example, via [--max-variants-per-shard](https://gatk.broadinstitute.org/hc/en-us/articles/5257852670107-SelectVariants#--max-variants-per-shard) on some tools, although I'm not sure how widely used or adopted that convention is.)

**Comment by jeromekelleher** [comment]
Aha, that's great!

I'd be more interested in single-threaded throughput than parallelisation to be honest. If we can get single threaded output performance up to the level that (say) bcftools can consume it in an old-skool unix pipeline, that'll fulfil 99% of use-cases I would say. I don't think there'll be that many uses for generating independent shards of the VCF.

**Comment by tomwhite** [comment]
> There is actually already support for [converting sgkit datasets to VCF](https://github.com/pystatgen/sgkit/blob/6554e54d5808ba975d73d84c93976ba807076f3d/sgkit/tests/io/vcf/vcf_writer.py#L131-L201), which I wrote a while back for testing purposes. This is Option 1 in your categorisation.

I misrepresented this - as it doesn't actually use the cyvcf2 API! (I seem to remember it wasn't flexible enough to write everything I wanted it to.) Instead it creates VCF lines as strings directly, but not in the efficient way discussed in Option 3.

So I think the work needed to improve this would be to make it more efficient (Option 3), or try one of the other options.

**Comment by timothymillar** [comment]
I'm curious about what the API for this could look like. Is the intention to allow the inclusion of arbitrary dataset variables into the VCF? If so, could data column (INFO/FORMAT) and length (1/A/G etc.) be inferred/mapped from the dataset dimensions directly?

I imagine that translating sentinel values to missing values`'.'` may require some explicit user input.

**Comment by jeromekelleher** [comment]
I guess it's just datasets that were originally in VCF that we've converted that we're aiming at, so the round-trip should be OK most of the time without requiring extra parameters?

**Comment by tomwhite** [comment]
> I imagine that translating sentinel values to missing values`'.'` may require some explicit user input.

It should be possible to do the mapping using the information stored in Zarr, see https://github.com/pystatgen/vcf-zarr-spec/blob/main/vcf_zarr_spec.md#missing-and-fill-values. Or is there a case that you're thinking of that seems like it might be a problem?

> I guess it's just datasets that were originally in VCF that we've converted that we're aiming at, so the round-trip should be OK most of the time without requiring extra parameters?

@jeromekelleher is your use case just for round-tripping?

We can cover that now, as we've got code that [tests lossless round-tripping](https://github.com/pystatgen/sgkit/blob/4b6671508ec07fea0855233f240c84352ffafda0/sgkit/tests/io/vcf/test_vcf_lossless_conversion.py), but it relies on being able to access the VCF header for the input (which is stored in a Zarr attribute), and that it doesn't change for the output.

But there may be cases where a new field is added that needs to be exported, so in that case it might be necessary to supply extra parameters. 

Another thing to bear in mind is that when converting from VCF to Zarr we need to be careful about how big array dimensions need to be to store all the data in the VCF losslessly. There is a function [`zarr_array_sizes `](https://github.com/pystatgen/sgkit/blob/4b6671508ec07fea0855233f240c84352ffafda0/sgkit/io/vcf/vcf_reader.py#L979) that can help with this by finding how big `Number=.` fields are for example (although it doesn't run in parallel).

**Comment by jeromekelleher** [comment]
> But there may be cases where a new field is added that needs to be exported, so in that case it might be necessary to supply extra parameters.

Yes, that's a good point. We should keep this in mind, as we would want to support outputting "new" columns to the VCF.

**Comment by timothymillar** [comment]
+1 for the ability to export custom variables to VCF. I think it'd be quite a compelling feature for experimental analyses.

**Comment by tomwhite** [comment]
I've started this by looking at approach 2 (Write the VCF text directly ourselves using numba), inspired by the tskit code that @jeromekelleher linked to earlier.

The hard part to do well on performance-wise is writing the format fields for large numbers of samples, since in VCF the format values are written in order for each sample, which goes against the way they are stored in Zarr. For example, if the fields are GT and HQ, then for n samples they are written out to VCF as:

```
GT1:HQ1 GT2:HQ2 GT3:HQ3 ... GTn:HQn
```

where GTi is the GT field for the i-th sample, and HQi is the HQ field for the i-th sample. This is further complicated by the fact that the values may have a variable width since they are strings, so an int field could be simply "1" or it might be "100000".

I've broken the problem into two steps.

The first takes a NumPy array of values and converts it to the character representations in another array, and at the same time creates an array of indexes into that array of the start positions of each value. So the values `[1, 34, 5, 67]` would become `[49, 51, 52, 53, 54, 55]` (ASCII values) and the index array would be `[0, 1, 3, 4, 6]`. This solves the variable width problem.

The second step then uses the character and index arrays from multiple fields and then interleaves them in the way described above. This can be made very efficient as it's just a copy operation.

Crucially, all of this can use preallocated arrays (for each variant row) and is numba-jitted. With the code in https://github.com/pystatgen/sgkit/commit/dd1d2db9e6ff84fb438746f136eaac6a4b6477a2 I can get around 200MB/s on my machine for the interleave process with 3 fields and 100,000 samples, which is encouraging.

**Comment by benjeffery** [comment]
Sounds great, the array tricks you are using are what I'd expect to be the fastest way.

**Comment by tomwhite** [comment]
This is complete
