### ISSUE TITLE
potential issue in how `ds.variant_allele` is populated in `read_plink`

### ISSUE THREAD

**Issue by clwgg** [pystatgen/sgkit#947]
Hi all! I'd greatly appreciate some clarification if the following test case shows intended behavior, or if there might be an issue with how alleles in `ds.variant_allele` are associated with their corresponding count data when reading data from plink:

We'll set up two SNPs, one A/G SNP with minor allele A at MAF=0.3, and one T/C SNP with minor allele T at MAF=0.4.
`test.ped`:
```
ind0 ind0 0 0 0 0 A A T T
ind1 ind1 0 0 0 0 A A T T
ind2 ind2 0 0 0 0 A A T T
ind3 ind3 0 0 0 0 G G T T
ind4 ind4 0 0 0 0 G G C C
ind5 ind5 0 0 0 0 G G C C
ind6 ind6 0 0 0 0 G G C C
ind7 ind7 0 0 0 0 G G C C
ind8 ind8 0 0 0 0 G G C C
ind9 ind9 0 0 0 0 G G C C
```

`test.map` (dummy data needed for conversion):
```
1 1_10 0 10
1 1_20 0 20
```
 and covert it to plink binary format:
``` bash
plink --file test --make-bed --out test
```

running this through `read_plink` with default parameters shows that the alleles are incorrectly associated with the count data:
``` python
import sgkit as sg
from sgkit.io.plink import read_plink

ds = read_plink(path="test")
ds = sg.call_allele_frequencies(ds)

print(ds.call_allele_frequency.mean(dim="samples").values)
print(ds.variant_allele.values)
```
```
[[0.7 0.3]
 [0.6 0.4]]
[[b'A' b'G']
 [b'T' b'C']]
```
i.e. A and T are incorrectly identified as the major, rather than the minor alleles for our two SNPs:
``` python
print(ds.isel(alleles=0).call_allele_frequency.mean(dim="samples").values)
print(ds.isel(alleles=0).variant_allele.values)
```
```
[0.7 0.6]
[b'A' b'T']
```

However, `read_plink` has the option `count_a1` which defaults to `True`. Setting it to `False` correctly associates the alleles with their counts:
``` python
import sgkit as sg
from sgkit.io.plink import read_plink

ds = read_plink(path="test", count_a1=False)
ds = sg.call_allele_frequencies(ds)

print(ds.call_allele_frequency.mean(dim="samples").values)
print(ds.variant_allele.values)
```
```
[[0.3 0.7]
 [0.4 0.6]]
[[b'A' b'G']
 [b'T' b'C']]
```

My issue with this is that the doc string for `count_a1` says:
```
        Whether or not allele counts should be for A1 or A2,
        by default True. Typically A1 is the minor allele
        and should be counted instead of A2. This is not enforced
        by PLINK though and it is up to the data generating process
        to ensure that A1 is in fact an alternate/minor/effect
        allele.
```
Inspecting the relevant `.bim` file shows that A1 is in fact the minor allele:
`test.bim`:
```
1	1_10	0	10	A	G
1	1_20	0	20	T	C
```
So I think we should be in the regime that's supposed to be covered by the default parameter, but isn't.

**Comment by tomwhite** [comment]
Thanks for raising the issue @clwgg and for the detailed description.

Do you think there is a case missing from the tests in https://github.com/pystatgen/sgkit/blob/82aa8171445244994434067fc51564f78debc44c/sgkit/tests/io/plink/test_plink_reader.py that would expose the problem?

**Comment by clwgg** [comment]
hmm, I don't see any test explicitly checking the values of `ds1.variant_allele`. running plink with `--freq` on the test dataset would give the right allele frequencies (hopefully), e.g.:
``` bash
plink --bfile plink_sim_10s_100v_10pmiss --freq --out plink_sim_10s_100v_10pmiss
```
(see also: https://www.cog-genomics.org/plink/1.9/formats#frq)

using the data in the plink `frq` file, the identity of the minor allele could then be tested for explicitly, e.g.:
``` python
test_idx = np.array([0, 2, 5, 6, 7, 8])
test_expected = np.array(['G', 'ACT', 'ACT', 'CGCGCG', 'T', 'T'], dtype=np.dtype("|S6"))
ds_sub = sg.call_allele_frequencies(ds1.isel(variants=test_idx))
minor_allele = ds_sub.call_allele_count.sum(dim="samples").argmin(dim="alleles")
np.testing.assert_equal(
    ds_sub.variant_allele.values[np.arange(len(minor_allele)), minor_allele.values],
    test_expected)
``` 
(which currently fails)

**Comment by tomwhite** [comment]
Hi @clwgg - thanks for providing a failing test. I have created a branch with it in, along with a possible fix in https://github.com/pystatgen/sgkit/compare/main...tomwhite:sgkit:read_plink_counts_bug. Here's some more detail on what I found out:

There is a known issue of how Plink 1.x handles allele ordering (see https://www.biostars.org/p/9495739/#9495908 and https://www.cog-genomics.org/plink/1.9/data#ax_allele).

In sgkit `read_plink` A1 is always the first allele and A2 is always the second allele in `variant_allele` - there is never any reordering. 

The `count_a1` parameter is passed to `bed_reader` to indicate if the A1 allele is the the one counted in genotypes (defaults to True). For example, if A1 is A and A2 is G then AA would be 2, AG or GA would be 1, and GG would be 0.

sgkit `read_plink` will then convert these genotypes to add a ploidy dimension. So 2 is [1, 1], 1 is [1, 0] (there is no phasing information), and 0 is [0, 0].

This seems to be where the problem is: AA should be encoded as [0, 0] since A has index 0 in `variant_allele`. Similarly GG should be [1, 1].

Setting `count_a1` to False fixes this (as you observed).

I notice that in the GWAS work that @eric-czech did (which, as far as I know, is the main usage of plink data in sgkit to date), `count_a1` is set to False: https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/blob/231d0e6e74772d1ae56205723952a5fff955aa74/scripts/convert_genetic_data.py#L69 

So can we just remove the `count_a1` parameter from `read_plink`? The True case seems to be buggy and is probably unused (for that reason).

**Comment by clwgg** [comment]
Hi @tomwhite - thank you for your investigation! I agree that in this case we probably just want to set `count_a1` to `False`. I wonder if we would want to remove the argument altogether, as you suggest, or simply "fix" the default value? While I haven't come across it myself, I suppose it's possible for a `plink` dataset to be malformed in the way that a user may want to set it to `True`, since, as you observed as well, `plink` doesn't enforce allele ordering either.

**Comment by tomwhite** [comment]
I'd be fine changing the default to False, as it seems to be a better default.

We'd still need to fix the True case though, and I'm not totally sure what that looks like, since I haven't come across it either. Here's a sketch of something that might work, although I'm not sure if having `count_a1` is any use, as the `plink_reader` code is basically undoing what `bed_reader` does: https://github.com/pystatgen/sgkit/compare/main...tomwhite:read_plink_counts_bug2

So perhaps we should drop it, and then if users have a case that can't be loaded properly using `read_plink` then we can work out what is needed to support it when we have a more concrete example? It might be that `count_a1` isn't the right thing to expose to users, and instead we need to reorder alleles or something.

**Comment by jeromekelleher** [comment]
I think unless someone has a use-case for True we should probably disable it. There's no point in spending time on something that nobody uses. 

How about we change the default for ``count_a1`` to False, and raise an error saying "count_a1=True is currently not supported, please open an issue if this is something you need".

That way we don't break anyone's code.

**Comment by tomwhite** [comment]
Thanks for the suggestion. A PR to do this is here: #952

**Comment by clwgg** [comment]
I think that all makes sense -- thanks a lot @tomwhite @jeromekelleher !
